"""Export utilities for summaries."""

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib import colors
from docx import Document
from docx.shared import Inches, Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
import markdown
from datetime import datetime
from io import BytesIO
from typing import Dict


class SummaryExporter:
    """Export summaries to various formats."""
    
    @staticmethod
    def export_to_pdf(summary_data: Dict) -> BytesIO:
        """Export summary to PDF format.
        
        Args:
            summary_data: Dictionary containing summary information
            
        Returns:
            BytesIO object containing PDF data
        """
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []
        
        # Custom styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#667eea'),
            spaceAfter=30,
            alignment=1  # Center
        )
        
        heading_style = ParagraphStyle(
            'CustomHeading',
            parent=styles['Heading2'],
            fontSize=14,
            textColor=colors.HexColor('#667eea'),
            spaceAfter=12,
            spaceBefore=12
        )
        
        # Title
        story.append(Paragraph("Content Summary Report", title_style))
        story.append(Spacer(1, 0.3 * inch))
        
        # Metadata table
        metadata = [
            ['Generated:', summary_data.get('timestamp', 'N/A')],
            ['Model:', summary_data.get('model_used', 'N/A')],
            ['Style:', summary_data.get('summary_style', 'Standard')],
            ['Original Length:', f"{summary_data.get('original_length', 0):,} characters"],
            ['Summary Length:', f"{summary_data.get('summary_length', 0):,} characters"],
            ['Compression:', summary_data.get('compression', 'N/A')],
        ]
        
        t = Table(metadata, colWidths=[2*inch, 4*inch])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.HexColor('#f0f0f0')),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
            ('TOPPADDING', (0, 0), (-1, -1), 8),
            ('GRID', (0, 0), (-1, -1), 1, colors.grey),
        ]))
        story.append(t)
        story.append(Spacer(1, 0.3 * inch))
        
        # Summary section
        story.append(Paragraph("Summary", heading_style))
        summary_text = summary_data.get('summary', 'No summary available')
        story.append(Paragraph(summary_text, styles['BodyText']))
        story.append(Spacer(1, 0.3 * inch))
        
        # Original text section (truncated if too long)
        story.append(Paragraph("Original Text", heading_style))
        original_text = summary_data.get('original_text', 'No original text available')
        if len(original_text) > 2000:
            original_text = original_text[:2000] + "... (truncated)"
        story.append(Paragraph(original_text, styles['BodyText']))
        
        # Footer
        story.append(Spacer(1, 0.5 * inch))
        footer_style = ParagraphStyle(
            'Footer',
            parent=styles['Normal'],
            fontSize=8,
            textColor=colors.grey,
            alignment=1
        )
        story.append(Paragraph(
            "Generated by Content Summarizer - Powered by Google Gemini AI",
            footer_style
        ))
        
        # Build PDF
        doc.build(story)
        buffer.seek(0)
        return buffer
    
    @staticmethod
    def export_to_word(summary_data: Dict) -> BytesIO:
        """Export summary to Word document format.
        
        Args:
            summary_data: Dictionary containing summary information
            
        Returns:
            BytesIO object containing Word document data
        """
        buffer = BytesIO()
        doc = Document()
        
        # Set document margins
        sections = doc.sections
        for section in sections:
            section.top_margin = Inches(1)
            section.bottom_margin = Inches(1)
            section.left_margin = Inches(1)
            section.right_margin = Inches(1)
        
        # Title
        title = doc.add_heading('Content Summary Report', 0)
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        title_run = title.runs[0]
        title_run.font.color.rgb = RGBColor(102, 126, 234)
        
        doc.add_paragraph()
        
        # Metadata table
        table = doc.add_table(rows=6, cols=2)
        table.style = 'Light Grid Accent 1'
        
        metadata_items = [
            ('Generated:', summary_data.get('timestamp', 'N/A')),
            ('Model:', summary_data.get('model_used', 'N/A')),
            ('Style:', summary_data.get('summary_style', 'Standard')),
            ('Original Length:', f"{summary_data.get('original_length', 0):,} characters"),
            ('Summary Length:', f"{summary_data.get('summary_length', 0):,} characters"),
            ('Compression:', summary_data.get('compression', 'N/A')),
        ]
        
        for i, (label, value) in enumerate(metadata_items):
            row = table.rows[i]
            row.cells[0].text = label
            row.cells[1].text = value
            # Bold the labels
            row.cells[0].paragraphs[0].runs[0].font.bold = True
        
        doc.add_paragraph()
        
        # Summary section
        summary_heading = doc.add_heading('Summary', 1)
        summary_heading.runs[0].font.color.rgb = RGBColor(102, 126, 234)
        
        summary_text = summary_data.get('summary', 'No summary available')
        summary_para = doc.add_paragraph(summary_text)
        summary_para.paragraph_format.line_spacing = 1.5
        
        doc.add_paragraph()
        
        # Original text section
        original_heading = doc.add_heading('Original Text', 1)
        original_heading.runs[0].font.color.rgb = RGBColor(102, 126, 234)
        
        original_text = summary_data.get('original_text', 'No original text available')
        if len(original_text) > 5000:
            original_text = original_text[:5000] + "\n\n... (truncated for document size)"
        
        original_para = doc.add_paragraph(original_text)
        original_para.paragraph_format.line_spacing = 1.5
        
        # Footer
        doc.add_paragraph()
        footer = doc.add_paragraph('Generated by Content Summarizer - Powered by Google Gemini AI')
        footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
        footer.runs[0].font.size = Pt(8)
        footer.runs[0].font.color.rgb = RGBColor(128, 128, 128)
        
        # Save to buffer
        doc.save(buffer)
        buffer.seek(0)
        return buffer
    
    @staticmethod
    def export_to_markdown(summary_data: Dict) -> str:
        """Export summary to Markdown format.
        
        Args:
            summary_data: Dictionary containing summary information
            
        Returns:
            Markdown formatted string
        """
        md_content = []
        
        # Title
        md_content.append("# Content Summary Report\n")
        
        # Metadata
        md_content.append("## Metadata\n")
        md_content.append(f"- **Generated:** {summary_data.get('timestamp', 'N/A')}")
        md_content.append(f"- **Model:** {summary_data.get('model_used', 'N/A')}")
        md_content.append(f"- **Style:** {summary_data.get('summary_style', 'Standard')}")
        md_content.append(f"- **Original Length:** {summary_data.get('original_length', 0):,} characters")
        md_content.append(f"- **Summary Length:** {summary_data.get('summary_length', 0):,} characters")
        md_content.append(f"- **Compression:** {summary_data.get('compression', 'N/A')}\n")
        
        # Summary
        md_content.append("## Summary\n")
        md_content.append(summary_data.get('summary', 'No summary available'))
        md_content.append("\n")
        
        # Original text
        md_content.append("## Original Text\n")
        original_text = summary_data.get('original_text', 'No original text available')
        if len(original_text) > 5000:
            original_text = original_text[:5000] + "\n\n... (truncated)"
        md_content.append(original_text)
        md_content.append("\n")
        
        # Footer
        md_content.append("---")
        md_content.append("*Generated by Content Summarizer - Powered by Google Gemini AI*")
        
        return "\n".join(md_content)
    
    @staticmethod
    def export_to_text(summary_data: Dict) -> str:
        """Export summary to plain text format.
        
        Args:
            summary_data: Dictionary containing summary information
            
        Returns:
            Plain text formatted string
        """
        lines = []
        
        lines.append("=" * 80)
        lines.append("CONTENT SUMMARY REPORT")
        lines.append("=" * 80)
        lines.append("")
        
        lines.append("METADATA")
        lines.append("-" * 80)
        lines.append(f"Generated:       {summary_data.get('timestamp', 'N/A')}")
        lines.append(f"Model:           {summary_data.get('model_used', 'N/A')}")
        lines.append(f"Style:           {summary_data.get('summary_style', 'Standard')}")
        lines.append(f"Original Length: {summary_data.get('original_length', 0):,} characters")
        lines.append(f"Summary Length:  {summary_data.get('summary_length', 0):,} characters")
        lines.append(f"Compression:     {summary_data.get('compression', 'N/A')}")
        lines.append("")
        
        lines.append("SUMMARY")
        lines.append("-" * 80)
        lines.append(summary_data.get('summary', 'No summary available'))
        lines.append("")
        
        lines.append("ORIGINAL TEXT")
        lines.append("-" * 80)
        original_text = summary_data.get('original_text', 'No original text available')
        if len(original_text) > 5000:
            original_text = original_text[:5000] + "\n\n... (truncated)"
        lines.append(original_text)
        lines.append("")
        
        lines.append("=" * 80)
        lines.append("Generated by Content Summarizer - Powered by Google Gemini AI")
        lines.append("=" * 80)
        
        return "\n".join(lines)
